cherrybomb: deprecate
```
==> /opt/homebrew/Cellar/cherrybomb/1.0.1/bin/cherrybomb --file=/private/tmp/cherrybomb-test-20240213-539-a3afav/api-with-examples.yaml --format json
Error: error sending request for url (https://cherrybomb.blstsecurity.com/tel): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known

Caused by:
    0: error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
    1: dns error: failed to lookup address information: nodename nor servname provided, or not known
    2: failed to lookup address information: nodename nor servname provided, or not known
```

Signed-off-by: Rui Chen <rui@chenrui.dev>