luacheck 1.2.0
Signed-off-by: Rui Chen <rui@chenrui.dev>

luacheck: update build

seeing some build error with `--global` flag, switch to use `--local`

```
==> luarocks make --tree=/opt/homebrew/Cellar/luacheck/1.2.0/libexec --global --lua-dir=/opt/homebrew/opt/lua

Error: Your user does not have write permissions in /opt/homebrew/lib/luarocks/rocks-5.4

You may want to run as a privileged user,
or use --local to install into your local tree at /private/tmp/luacheck-20240524-2422-18lbhe/luacheck-1.2.0/.brew_home/.luarocks
or run 'luarocks config local_by_default true' to make --local the default.

(You may need to configure your Lua package paths
to use the local tree, see 'luarocks path --help')
```

Signed-off-by: Rui Chen <rui@chenrui.dev>